steps:
  - group: ":globe_with_meridians: Web"
    key: web
    if_changed: ["web/**", "*.{json,mjs,cjs}", ".buildkite/**"]
    steps:
      - label: ":eslint: Lint"
        command:
          - ".buildkite/scripts/install.sh"
          - "npm run lint -w web"

      - label: ":jest: Unit"
        parallelism: 4
        command:
          - ".buildkite/scripts/install.sh"
          - "bktec run"
        plugins:
          - tests#v1.0.1:
              test-runner: jest
              result-path: jest-results.json
              test-file-pattern: "web/tests/**/*.test.ts"

      - label: ":package: Build"
        key: build
        command:
          - ".buildkite/scripts/install.sh"
          - "npm run build -w web"
        artifact_paths: "web/dist/**/*"

      - label: ":playwright: E2E"
        depends_on: build
        command:
          - ".buildkite/scripts/install.sh"
          - "buildkite-agent artifact download 'web/dist/**' ."
          - "npx playwright install-deps chromium"
          - "npx playwright install chromium"
          - "echo '--- :playwright: Run E2E'"
          - "npm run e2e -w web"

  - label: ":bust_in_silhouette: Account"
    if_changed: ["account/**", "*.{json,mjs,cjs}", ".buildkite/**"]
    command:
      - ".buildkite/scripts/install.sh"
      - "npm run lint -w account"
      - "npm test -w account"

  - wait

  - group: ":rocket: Deploy"
    if: build.branch == "main"
    steps:
      - label: ":rocket: Deploy"
        command: "bash .buildkite/scripts/deploy.sh"
        secrets:
          - DEPLOY_KEY
